### PR TITLE
Generate modules for Python bindings

### PR DESCRIPTION
**Pull request by edgarv**
Currently MaterialX python bindings, generated through pybind11, were generated as shared libraries. Along with the version/soname information, this was generating additional files on Linux and macOS: the versioned library and two symlinks. When packaging the binary components, these files would be duplicated as zip-based python packages do not support symbolic links, they just store full copies of the files. On Windows, this avoids installing a .lib file (which will never get used) along the .pyd files.

Also, add a small fix to the python test scripts so that they work when the source code resides in a read-only location.

### CODE REVIEW

**Comment by edgarv** [comment]
The main python test is failing in the macOS slaves, I cannot replicate the error locally. From the Travis console:

<https://github.com/edgarv/MaterialX/blob/98408e394c2c1e50801191531c9763ecba02ccd6/python/MaterialXTest/main.py#L475>

```
CustomNode.mtlx is not valid :
Invalid port connection: <input name="in1" type="color3" nodename="n1">
Invalid port connection: <output name="out" type="color3" nodename="n2">
Invalid port connection: <input name="fg" type="color3" nodename="img1">
Invalid port connection: <input name="bg" type="color3" nodename="img2">
Invalid port connection: <output name="blended" type="color3" nodename="bl1">
```

**Comment by ashwinbhat** [comment]
@edgarv I think MaterialX Python is require Python 3. Can we update the travis setup to use pyhton 3?
https://docs.travis-ci.com/user/languages/python/

**Comment by edgarv** [comment]
Some more information about the Python 2 failure on macOS:

* It does not happen when compiling without optimizations.
* Building with `-O1` triggers a segmentation fault.
* Building with `-O1 -g -fsanitize=undefined` finds some invalid pointer type usage inside pybind.

Output with `O1 -g -fsanizie=undefined`:

```console
$ /usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python main.py
/Dev/github.com/autodesk-forks/MaterialX/source/PyMaterialX/PyBind11/include/pybind11/detail/class.h:328:17: runtime error: call to function pybind11::class_<MaterialX::FileSearchPath>::dealloc(pybind11::detail::value_and_holder&) through pointer to incorrect function type 'void (*)(pybind11::detail::value_and_holder &)'
pybind11.h:1349: note: pybind11::class_<MaterialX::FileSearchPath>::dealloc(pybind11::detail::value_and_holder&) defined here
...
----------------------------------------------------------------------
Ran 6 tests in 3.694s

OK
```

Output with `-O1 -g -fsanize=address`:

```console
$ /usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python main.py
...AddressSanitizer:DEADLYSIGNAL
=================================================================
==90696==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0001072f2fb5 bp 0x7ffeef5a4130 sp 0x7ffeef5a4120 T0)
==90696==The signal is caused by a READ memory access.
==90696==Hint: address points to the zero page.
    #0 0x1072f2fb4 in MaterialX::ScopedUpdate::ScopedUpdate(std::__1::shared_ptr<MaterialX::Document>) Document.h
    #1 0x1071489db in MaterialX::Element::clearContent() Element.cpp:425
    #2 0x1070e399c in MaterialX::Document::initialize() Document.cpp:143
    #3 0x1070e334b in std::__1::shared_ptr<MaterialX::Document> MaterialX::Document::createDocument<MaterialX::Document>() Document.h:44
    #4 0x1070e322d in MaterialX::createDocument() Document.cpp:42
    #5 0x1072ea896 in MaterialX::(anonymous namespace)::processXIncludes(std::__1::shared_ptr<MaterialX::Document>, pugi::xml_node&, MaterialX::FileSearchPath const&, MaterialX::XmlReadOptions const*) XmlIo.cpp:183
    #6 0x1072e70c7 in MaterialX::(anonymous namespace)::documentFromXml(std::__1::shared_ptr<MaterialX::Document>, pugi::xml_document const&, MaterialX::FileSearchPath const&, MaterialX::XmlReadOptions const*) XmlIo.cpp:237
    #7 0x1072e6826 in MaterialX::readFromXmlFile(std::__1::shared_ptr<MaterialX::Document>, MaterialX::FilePath const&, MaterialX::FileSearchPath const&, MaterialX::XmlReadOptions const*) XmlIo.cpp:320
    #8 0x1070cd0b3 in void pybind11::detail::argument_loader<std::__1::shared_ptr<MaterialX::Document>, MaterialX::FilePath const&, MaterialX::FileSearchPath const&, MaterialX::XmlReadOptions const*>::call_impl<void, void (*&)(std::__1::shared_ptr<MaterialX::Document>, MaterialX::FilePath const&, MaterialX::FileSearchPath const&, MaterialX::XmlReadOptions const*), 0ul, 1ul, 2ul, 3ul, pybind11::detail::void_type>(void (*&&&)(std::__1::shared_ptr<MaterialX::Document>, MaterialX::FilePath const&, MaterialX::FileSearchPath const&, MaterialX::XmlReadOptions const*), pybind11::detail::index_sequence<0ul, 1ul, 2ul, 3ul>, pybind11::detail::void_type&&) cast.h:1935
    #9 0x1070ca3c3 in std::__1::enable_if<std::is_void<void>::value, pybind11::detail::void_type>::type pybind11::detail::argument_loader<std::__1::shared_ptr<MaterialX::Document>, MaterialX::FilePath const&, MaterialX::FileSearchPath const&, MaterialX::XmlReadOptions const*>::call<void, pybind11::detail::void_type, void (*&)(std::__1::shared_ptr<MaterialX::Document>, MaterialX::FilePath const&, MaterialX::FileSearchPath const&, MaterialX::XmlReadOptions const*)>(void (*&&&)(std::__1::shared_ptr<MaterialX::Document>, MaterialX::FilePath const&, MaterialX::FileSearchPath const&, MaterialX::XmlReadOptions const*)) && cast.h:1917
    #10 0x1070c9d38 in void pybind11::cpp_function::initialize<void (*&)(std::__1::shared_ptr<MaterialX::Document>, MaterialX::FilePath const&, MaterialX::FileSearchPath const&, MaterialX::XmlReadOptions const*), void, std::__1::shared_ptr<MaterialX::Document>, MaterialX::FilePath const&, MaterialX::FileSearchPath const&, MaterialX::XmlReadOptions const*, pybind11::name, pybind11::scope, pybind11::sibling, pybind11::arg, pybind11::arg, pybind11::arg_v, pybind11::arg_v>(void (*&&&)(std::__1::shared_ptr<MaterialX::Document>, MaterialX::FilePath const&, MaterialX::FileSearchPath const&, MaterialX::XmlReadOptions const*), void (*)(std::__1::shared_ptr<MaterialX::Document>, MaterialX::FilePath const&, MaterialX::FileSearchPath const&, MaterialX::XmlReadOptions const*), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const pybind11.h:160
    #11 0x107018311 in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) pybind11.h:624
    #12 0x1013c9566 in PyEval_EvalFrameEx (Python:x86_64+0x86566)
    #13 0x1013cd8f6 in fast_function (Python:x86_64+0x8a8f6)
    #14 0x1013c9403 in PyEval_EvalFrameEx (Python:x86_64+0x86403)
    #15 0x1013c40f5 in PyEval_EvalCodeEx (Python:x86_64+0x810f5)
    #16 0x10136aee1 in function_call (Python:x86_64+0x27ee1)
    #17 0x10134d645 in PyObject_Call (Python:x86_64+0xa645)
    #18 0x1013c9d8a in PyEval_EvalFrameEx (Python:x86_64+0x86d8a)
    #19 0x1013c40f5 in PyEval_EvalCodeEx (Python:x86_64+0x810f5)
    #20 0x10136aee1 in function_call (Python:x86_64+0x27ee1)
    #21 0x10134d645 in PyObject_Call (Python:x86_64+0xa645)
    #22 0x101357e31 in instancemethod_call (Python:x86_64+0x14e31)
    #23 0x10134d645 in PyObject_Call (Python:x86_64+0xa645)
    #24 0x101392f77 in slot_tp_call (Python:x86_64+0x4ff77)
    #25 0x10134d645 in PyObject_Call (Python:x86_64+0xa645)
    #26 0x1013c9550 in PyEval_EvalFrameEx (Python:x86_64+0x86550)
    #27 0x1013c40f5 in PyEval_EvalCodeEx (Python:x86_64+0x810f5)
    #28 0x10136aee1 in function_call (Python:x86_64+0x27ee1)
    #29 0x10134d645 in PyObject_Call (Python:x86_64+0xa645)
    #30 0x1013c9d8a in PyEval_EvalFrameEx (Python:x86_64+0x86d8a)
    #31 0x1013c40f5 in PyEval_EvalCodeEx (Python:x86_64+0x810f5)
    #32 0x10136aee1 in function_call (Python:x86_64+0x27ee1)
    #33 0x10134d645 in PyObject_Call (Python:x86_64+0xa645)
    #34 0x101357e31 in instancemethod_call (Python:x86_64+0x14e31)
    #35 0x10134d645 in PyObject_Call (Python:x86_64+0xa645)
    #36 0x101392f77 in slot_tp_call (Python:x86_64+0x4ff77)
    #37 0x10134d645 in PyObject_Call (Python:x86_64+0xa645)
    #38 0x1013c9550 in PyEval_EvalFrameEx (Python:x86_64+0x86550)
    #39 0x1013c40f5 in PyEval_EvalCodeEx (Python:x86_64+0x810f5)
    #40 0x10136aee1 in function_call (Python:x86_64+0x27ee1)
    #41 0x10134d645 in PyObject_Call (Python:x86_64+0xa645)
    #42 0x1013c9d8a in PyEval_EvalFrameEx (Python:x86_64+0x86d8a)
    #43 0x1013c40f5 in PyEval_EvalCodeEx (Python:x86_64+0x810f5)
    #44 0x10136aee1 in function_call (Python:x86_64+0x27ee1)
    #45 0x10134d645 in PyObject_Call (Python:x86_64+0xa645)
    #46 0x101357e31 in instancemethod_call (Python:x86_64+0x14e31)
    #47 0x10134d645 in PyObject_Call (Python:x86_64+0xa645)
    #48 0x101392f77 in slot_tp_call (Python:x86_64+0x4ff77)
    #49 0x10134d645 in PyObject_Call (Python:x86_64+0xa645)
    #50 0x1013c9550 in PyEval_EvalFrameEx (Python:x86_64+0x86550)
    #51 0x1013cd8f6 in fast_function (Python:x86_64+0x8a8f6)
    #52 0x1013c9403 in PyEval_EvalFrameEx (Python:x86_64+0x86403)
    #53 0x1013cd8f6 in fast_function (Python:x86_64+0x8a8f6)
    #54 0x1013c9403 in PyEval_EvalFrameEx (Python:x86_64+0x86403)
    #55 0x1013c40f5 in PyEval_EvalCodeEx (Python:x86_64+0x810f5)
    #56 0x10136aee1 in function_call (Python:x86_64+0x27ee1)
    #57 0x10134d645 in PyObject_Call (Python:x86_64+0xa645)
    #58 0x101357e31 in instancemethod_call (Python:x86_64+0x14e31)
    #59 0x10134d645 in PyObject_Call (Python:x86_64+0xa645)
    #60 0x1013939c0 in slot_tp_init (Python:x86_64+0x509c0)
    #61 0x101390bc2 in type_call (Python:x86_64+0x4dbc2)
    #62 0x10134d645 in PyObject_Call (Python:x86_64+0xa645)
    #63 0x1013c9550 in PyEval_EvalFrameEx (Python:x86_64+0x86550)
    #64 0x1013c40f5 in PyEval_EvalCodeEx (Python:x86_64+0x810f5)
    #65 0x1013c3ed9 in PyEval_EvalCode (Python:x86_64+0x80ed9)
    #66 0x1013e5c08 in run_mod (Python:x86_64+0xa2c08)
    #67 0x1013e5caf in PyRun_FileExFlags (Python:x86_64+0xa2caf)
    #68 0x1013e5836 in PyRun_SimpleFileExFlags (Python:x86_64+0xa2836)
    #69 0x1013f6f0f in Py_Main (Python:x86_64+0xb3f0f)
    #70 0x7fff6aa7e3d4 in start (libdyld.dylib:x86_64+0x163d4)

==90696==Register values:
rax = 0x0000000000000000  rbx = 0x00007ffeef5a4180  rcx = 0x00000000000000a0  rdx = 0x0000000000000000  
rdi = 0x00007ffeef5a4180  rsi = 0x00007ffeef5a41a8  rbp = 0x00007ffeef5a4130  rsp = 0x00007ffeef5a4120  
 r8 = 0x0000000000000000   r9 = 0x00000fffffffffff  r10 = 0x0000000000000000  r11 = 0xffffffffffffffff  
r12 = 0x00007ffeef5a41a0  r13 = 0x00007ffeef5a4160  r14 = 0x0000100000000000  r15 = 0x00001fffddeb4828  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV Document.h in MaterialX::ScopedUpdate::ScopedUpdate(std::__1::shared_ptr<MaterialX::Document>)
==90696==ABORTING
Abort trap: 6
```

Local clang version, running on macOS 10.14.6:

```console
$ c++ --version
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by bernardkwok** [comment]
Do folks still want to continue with this PR as it's been sitting around for quite a while. If not can we close it? Thanks.

**Pull request closed without merging**
