### PR TITLE
chore: Address vulnerability issues

### PR DESCRIPTION
**Pull request by kohakukun**
Update #1304

### CODE REVIEW

**Comment by kohakukun** [comment]
@bernardkwok @ashwinbhat In general package-lock.json should not be removed. It is what give a deterministic build. Updates are usually done manually or by a bot that updates the packge-lock

**Comment by ashwinbhat** [comment]
> @bernardkwok @ashwinbhat In general package-lock.json should not be removed. It is what give a deterministic build. Updates are usually done manually or by a bot that updates the packge-lock

Hi @kohakukun 
The issue is the package-lock.json cannot point to `https://art-bobcat.autodesk.com:443` in public repo. Can you submit a package-lock that is pointing to public npm?

**Review by ashwinbhat — COMMENTED** [review]
Can we remove reference to https://art-bobcat.autodesk.com:443?

**Comment by bernardkwok** [comment]
Yes. As Ashwin notes, the reason is that we cannot point to Autodesk servers when we merge to ILM main.

**Comment by kohakukun** [comment]
Good catch. Forgot about that. I just updated the package-lock.json with the public npm registry

**Review by bernardkwok — APPROVED** [review]
Thanks for the fix Aura.

**Review by ashwinbhat — APPROVED** [review]

**Pull request merged**
